apiVersion: v1
kind: Pod
metadata:
  name: ubuntu1
  namespace: default
spec:
  containers:
  - image: 192.168.56.201:5000/my-ubuntu:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
