apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-jobservice-config
data:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_USR: root
  MYSQL_PWD: "root123"
#  UI_SECRET: "q0m5eaqXNs4nbVhF"
#  SECRET_KEY: "eSfTocKs5BxHFe14"
  UI_SECRET: "RBQNFKVrER1IabT5"
  JOBSERVICE_SECRET: "YFJkh9emCcB2pVHf"
  CONFIG_PATH: /etc/jobservice/app.conf
  REGISTRY_URL: http://registry:5000
  VERIFY_REMOTE_CERT: "on"
  MAX_JOB_WORKERS: "3"
  LOG_LEVEL: debug
  LOG_DIR: /var/log/jobs
  GODEBUG: netdns=cgo
  EXT_ENDPOINT: "http://reg.mydomain.com"
  TOKEN_URL: http://ui
  secret-key: "isL2f9uiBN22Gss1"
  config: |
    appname = jobservice
    runmode = dev
    [dev]
    httpport = 80
