apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-adminserver-config
data:
  LOG_LEVEL: debug
  AUTH_MODE: db_auth
  SELF_REGISTRATION: "on"
  LDAP_URL: ldaps://ldap.mydomain.com
  LDAP_SEARCH_DN:
  LDAP_SEARCH_PWD:
  LDAP_BASE_DN: "ou=people,dc=mydomain,dc=com"
  LDAP_FILTER:
  LDAP_UID: uid
  LDAP_SCOPE: "3"
  LDAP_TIMEOUT: "5"
  DATABASE_TYPE: mysql
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_USR: root
  MYSQL_PWD: "root123"
  MYSQL_DATABASE: registry
  REGISTRY_URL: http://registry:5000
  TOKEN_SERVICE_URL: http://ui/service/token
  EMAIL_HOST: smtp.mydomain.com
  EMAIL_PORT: "25"
  EMAIL_USR: sample_admin@mydomain.com
  EMAIL_PWD: abc
  EMAIL_SSL: "false"
  EMAIL_FROM: "admin <sample_admin@mydomain.com>"
  EMAIL_IDENTITY:
  HARBOR_ADMIN_PASSWORD: "Harbor12345"
  PROJECT_CREATION_RESTRICTION: everyone
  VERIFY_REMOTE_CERT: "on"
  MAX_JOB_WORKERS: "3"
  UI_SECRET: "RBQNFKVrER1IabT5"
  JOBSERVICE_SECRET: "YFJkh9emCcB2pVHf"
  TOKEN_EXPIRATION: "30"
  CFG_EXPIRATION: "5"
  GODEBUG: "netdns=cgo"
  ADMIRAL_URL: NA
  WITH_NOTARY: "False"
  RESET: "true"
  EXT_ENDPOINT: "http://reg.mydomain.com"
  TOKEN_URL: http://ui
  secret-key: "isL2f9uiBN22Gss1"
  config: |
    {
      "admin_initial_password": "\u003cenc-v1\u003ejdwJ3RaNOH18U+gyvGAkH6RhS0X1Q3Ji6mn/",
      "admiral_url": "NA",
      "auth_mode": "db_auth",
      "cfg_expiration": 5,
      "clair_db_password": "\u003cenc-v1\u003eQPuwkTJmZBf5lKmoIWrH51M2Xbytv+Xv",
      "database_type": "mysql",
      "email_from": "admin \u003csample_admin@mydomain.com\u003e",
      "email_host": "smtp.mydomain.com",
      "email_identity": "",
      "email_password": "\u003cenc-v1\u003ehTCHf1nnl+3nt/rJDGdBSiStTA==",
      "email_port": 25,
      "email_ssl": false,
      "email_username": "sample_admin@mydomain.com",
      "ext_endpoint": "http://reg.mydomain.com",
      "ldap_base_dn": "ou=people,dc=mydomain,dc=com",
      "ldap_filter": "",
      "ldap_scope": 3,
      "ldap_search_dn": "",
      "ldap_search_password": "\u003cenc-v1\u003eir2BIOgIr+H+1kkpdmkQHw==",
      "ldap_timeout": 5,
      "ldap_uid": "uid",
      "ldap_url": "ldaps://ldap.mydomain.com",
      "max_job_workers": 3,
      "mysql_database": "registry",
      "mysql_host": "mysql",
      "mysql_password": "\u003cenc-v1\u003er/AqSLiRJZ31lYsOPPEa7V3Vnp7z4DM=",
      "mysql_port": 3306,
      "mysql_username": "root",
      "project_creation_restriction": "everyone",
      "registry_url": "http://registry:5000",
      "self_registration": true,
      "sqlite_file": "",
      "token_expiration": 30,
      "verify_remote_cert": true,
      "with_clair": false,
      "with_notary": false
    }
