apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-jobservice-config
data:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_USR: root
  MYSQL_PWD: "{{db_password}}"
  UI_SECRET: "{{ui_secret}}"
  SECRET_KEY: "{{secret_key}}"
  CONFIG_PATH: /etc/jobservice/app.conf
  REGISTRY_URL: http://registry:5000
  VERIFY_REMOTE_CERT: "{{verify_remote_cert}}"
  MAX_JOB_WORKERS: "{{max_job_workers}}"
  LOG_LEVEL: debug
  LOG_DIR: /var/log/jobs
  GODEBUG: netdns=cgo
  EXT_ENDPOINT: "{{ui_url}}"
  TOKEN_URL: http://ui
  config: |
    appname = jobservice
    runmode = dev
    [dev]
    httpport = 80
